// Code generated by "stringer -type=RelationKind -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeSimple-0]
	_ = x[TypeUnion-1]
	_ = x[TypeIntersection-2]
}

const _RelationKind_name = "TypeSimpleTypeUnionTypeIntersection"

var _RelationKind_index = [...]uint8{0, 10, 19, 35}

func (i RelationKind) String() string {
	if i < 0 || i >= RelationKind(len(_RelationKind_index)-1) {
		return "RelationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RelationKind_name[_RelationKind_index[i]:_RelationKind_index[i+1]]
}
